apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: staging
spec:
  replicas: 10
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: my-app-container
          image: harbor.korporate.org/my-app-image:main-c263a545b748b61debb3bb5a62914bd178919552
          imagePullPolicy: Always
          ports:
            - containerPort: 80
