apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: staging
spec:
  replicas: 10
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: my-app-container
          image: harbor.korporate.org/myapp/my-app-image:main-6e068164bf606b0cb5eaca395a0d3039b9be5b7f
          imagePullPolicy: Always
          ports:
            - containerPort: 80
