apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: staging
spec:
  replicas: 10
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: my-app-container
          image: harbor.korporate.org/myapp/my-app-image:main-82eaf9e44f6e286949c9e6580e72753a8bc6a61f
          imagePullPolicy: Always
          ports:
            - containerPort: 80
