name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      # If you wish to fail your job when the Quality Gate is red, uncomment the
      # following lines. This would typically be used to fail a deployment.
      # - uses: sonarsource/sonarqube-quality-gate-action@master
      #   timeout-minutes: 5
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - name: Start containers
        run: docker compose -f "docker-compose.yml" up -d --build
      # - name: wait 25s
      #   run: sleep 25
      # - name: Run tests
      #   run: docker compose exec -T php /var/www/app/vendor/vendor/bin/phpunit
      - name: Stop containers
        if: always()
        run: docker compose -f "docker-compose.yml" down
      - name: Build artifact
        run: docker build ./laravel -t harbor.korporate.org/myapp/myapp:${{ github.run_number }}
      - name: Push artifact to harbor
        run: docker push harbor.korporate.org/myapp/myapp:${{ github.run_number }}
      - name: Clone Repository
        run: git clone https://github.com/0769233558/myapp-argo-staging.git
      - name: Install yq
        run: |
          sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
          sudo chmod a+x /usr/local/bin/yq
      - name: Update YAML File
        run: yq -i '.spec.template.spec.containers[0].image = "harbor.korporate.org/myapp/myapp:${{ github.run_number }}"' 'argocd-configs/chaturmail-pod.yaml'
      - name: Push to Repo
        run: |
          git config --global user.name "${{secrets.USERNAME_GITHUB}}"
          git config --global user.email "${{secrets.EMAIL_GITHUB}}"
          cd myapp-argo-staging
          git add .
          git commit -m "Updated by GitHub Actions"
          git push https://github.com/0769233558/myapp-argo-staging.git --all